[package]
name = "rumqttd"
version = "0.1.0"
authors = ["tekjar <k.teza1@gmail.com>"]

[dependencies]
bytes = "0.4"
futures = "0.1"
tokio-io = "0.1"
tokio-core = "0.1"
tokio-timer = "0.1"
quick-error = "1.1"
slog = "2"
slog-term = "2.0.0-4.0"
slog-async = "2"
#mqtt3 = { git = "https://github.com/tekjar/mqtt3" }
mqtt3 = {path = "../mqtt3"}